### ISSUE TITLE
No blur-up effect?

### ISSUE THREAD

**Issue by robinmetral** [TylerBarnes/gatsby-wordpress-inline-images#1]
Hi :wave: 

First of all thanks for this plugin! The Gatsby+WordPress stack really needed it.

I've started using it and noticed that there isn't a blur-up effect as there is by default with other sharp plugins. Has it been disabled?

Similarly setting `tracedSVG` to `true` doesn't work. Or am I mistaken in thinking that the options are the same as in [`gatsby-remark-images`](https://www.gatsbyjs.org/packages/gatsby-remark-images/#options)?

**Comment by TylerBarnes** [comment]
Hey @robinmetral!
Yeah, Gatsby/WP definitely needs this. 
The reason for the missing blur up effect and missing remark settings is that this plugin is unfinished.
I've been meaning to put in the last 10% to finish this but I've been slammed with work, life, family, and other OSS stuff. 
If you know your way around gatsby and think you can get those features working I'd love a PR!
There's a history of this plugin at https://github.com/gatsbyjs/gatsby/issues/11179

**Comment by robinmetral** [comment]
Thanks for your reply @TylerBarnes!

I'll try to take a look at it but I'm not sure I know Gatsby well enough :slightly_smiling_face: 

Fortunately it's far from a breaking issue, I'm already  super happy with the plugin - thanks!

**Comment by TylerBarnes** [comment]
Upgrade to v1!
