### ISSUE TITLE
original filenames with sizes pattern

### ISSUE THREAD

**Issue by riencoertjens** [TylerBarnes/gatsby-wordpress-inline-images#15]
images with original file names containing the sizes pattern (like: 100x200) are not converted to a gatsby image object.
not sure where to go look to solve this problem so for now I replaces the files that gave me problems in my project.
Will try to make a pr to fix it in the near future, unless this can be fixed quickly by someone who knows the plugin?

**Comment by rgllm** [comment]
@riencoertjens I'm getting the same issue. How did you solve this?

**Comment by riencoertjens** [comment]
I ended up using something else, [this function](https://github.com/TylerBarnes/gatsby-wordpress-inline-images/blob/master/utils/parseWPImagePath.js) removes the dimensions from image filenames, so that's where it's going wrong if the image has the dimensions in the original filename.

**Comment by rgllm** [comment]
@riencoertjens I came to same conclusion 😆. I've done a function on WordPress side to automatically remove the image size from the image name when uploading a new file. If you want I can share it with you.

**Comment by TylerBarnes** [comment]
I think we could use try/catch here to attempt to DL the image with the dimensions removed (to get the full size image), and if it doesn't exist we could try again with the original URL that has the dimensions. That would probably solve it in this plugin

**Comment by rgllm** [comment]
@TylerBarnes that is probably the most user friendly way to deal with this problem. Happy to contribute if needed.

**Comment by TylerBarnes** [comment]
@rgllm that would be super helpful. Between my job and my other plugins I've been slammed the past 6 or so months. You can find the try/catch here https://github.com/TylerBarnes/gatsby-wordpress-inline-images/blob/c7d82a38ccd044d16f9ae61bd1468ba20e29ce92/src/gatsby-node.js#L231-L249

**Comment by TylerBarnes** [comment]
As a side note, the commented code is left in to implement image cacheing, which I have a really good idea on how to implement now that I've spent a bunch more time working on my custom gatsby WP source plugin.

**Comment by rgllm** [comment]
@TylerBarnes I have already forked the repository. I will work on this and make a PR when done.

**Comment by TylerBarnes** [comment]
Awesome!

**Comment by rgllm** [comment]
@TylerBarnes can you take a look into this? https://github.com/TylerBarnes/gatsby-wordpress-inline-images/pull/20

**Comment by TylerBarnes** [comment]
Fixed in `gatsby-wordpress-inline-images@1.1.0`. Thanks @rgllm

**Comment by rgllm** [comment]
Thanks @TylerBarnes 💪
