### ISSUE TITLE
Add more detailed explanations to Readme

### ISSUE THREAD

**Issue by sylflo** [TylerBarnes/gatsby-wordpress-inline-images#18]
I seriously must have missed something but I am not sure about a few things

I update `gatsby-node.js` like this
```
 resolve: "gatsby-source-wordpress",
      options: {
        baseUrl: "your-site.com",
        protocol: "http",
        maxWidth: 650,
        wrapperStyle: ``,
        postTypes: ["post", "page"],
        backgroundColor: `white`,
        withWebp: false,
        plugins: [
          {
            resolve: `gatsby-wordpress-inline-images`,
            options: {
              baseUrl: `your-site.com`,
              protocol: `http`
            },
          },
        ],
```

I make a grapql request so I went to the `GraphiQL` console and send this
```
{
  allWordpressPost {
    edges {
      node {
        id
     	content
      }
    }
  }
}
```

So far so good, now I have a base64 in the content property.
My question am I supposed to parse this base64 or is there a cleaner way to get the images ? Maybe using `imageSharp`

**Comment by TylerBarnes** [comment]
Hey @sylflo , this plugin is for `gatsby-source-wordpress`. I think you're looking for this -> https://www.gatsbyjs.org/packages/gatsby-wpgraphql-inline-images/

**Comment by TylerBarnes** [comment]
The images will be mixed into the HTML of your post content so this plugin should just work when you install it. If you parse the content into React you should be good! You can use `dangerouslySetInnerHtml` or this https://www.npmjs.com/package/react-html-parser

**Comment by sylflo** [comment]
Ah ok, I was being naive and stupid, I thought the plugin will send a list of images but it does make more sense to do what it actually does

**Comment by TylerBarnes** [comment]
No worries! It's an honest and not-stupid mistake. This is definitely the kind of issue I'd open myself 🤣 
 Let me know if you need any more help!
