### ISSUE TITLE
gatsby-wordpress-inline-images does not work for me, help appreciated

### ISSUE THREAD

**Issue by TomePale** [TylerBarnes/gatsby-wordpress-inline-images#27]
Hello @TylerBarnes maybe you can give me some tips why I can't get it to work. I am trying to pull out image from WordPress post and save it, I attached few images how my gatbsy-config.js looks like:
![Screenshot 2020-01-13 at 15 46 03](https://user-images.githubusercontent.com/9658088/72265019-0808cc80-361c-11ea-9480-91fd0e938b45.png)
![Screenshot 2020-01-13 at 15 48 15](https://user-images.githubusercontent.com/9658088/72265080-279ff500-361c-11ea-893e-80d027765152.png)

Also I got a warrning in build time:
![Screenshot 2020-01-13 at 15 43 46](https://user-images.githubusercontent.com/9658088/72265151-4605f080-361c-11ea-90fb-9f0e030164cb.png)

Regards,
Tome

**Comment by TylerBarnes** [comment]
@TomePale off the top of my head I'm not too sure. If you can share your repo I'm happy to take a look!

**Comment by TomePale** [comment]
@TylerBarnes sry its a private repo so I can't share it, however setup is basic, in **gatsby-node.js** I am iterating over all WP posts and then in a Blog Post template I am showing the post, basic stuff. **gatsby-source-wordpress** and **gatsby-image** are installed, you can see setup from attached image above.

Is there any additional configuration steps maybe or this plugin should work out of the box?

**Comment by TylerBarnes** [comment]
@TomePale thanks for the additional info! If you create a simple reproduction and link me to that I'm happy to take a look. Thanks!

**Comment by TomePale** [comment]
Sry for late respone, I found another solution that worked for me...Thx anyway.
