### ISSUE TITLE
Invalid plugin option - "plugins" must contain 0 items

### ISSUE THREAD

**Issue by MattFanto** [TylerBarnes/gatsby-wordpress-inline-images#35]
I followed the README instruction to setup the processing of inline images, in particular the section:

> Add this plugin as a plugin of gatsby-source-wordpress. Be sure to specify your baseurl and protocol a second time in the gatsby-wordpress-inline-images options, not just in the gatsby-source-wordpress options.

```
{
  resolve: `gatsby-source-wordpress`,
  options: {
    baseUrl: `your-site.com`
    protocol: `https`,
    plugins: [
        {
          resolve: `gatsby-wordpress-inline-images`,
          options: {
            baseUrl: `your-site.com`,
            protocol: `https`
          }
        }
      ]
    }
}
```

Unfortunately when I run develop I face the following error

```
Invalid plugin options for "gatsby-source-wordpress":

- "plugins" must contain 0 items
```

I was wondering if a particular version of `gatsby-source-wordpress` is required, my package.json has
```
"gatsby": "^2.32.0",
"gatsby-source-wordpress": "^4.0.4",
"gatsby-wordpress-inline-images": "^1.2.1",
```

**Comment by TylerBarnes** [comment]
Hi @MattFanto , this plugin is no longer needed actually. On the latest version of gatsby-source-wordpress I've included this functionality by default. Thanks for the reminder about this repo - I'll add a note to the readme and archive it.

Thanks!
