### ISSUE TITLE
Appears to attempt remote image fetching from localhost.

### ISSUE THREAD

**Issue by glennforrest** [TylerBarnes/gatsby-wordpress-inline-images#8]
Apologies if I'm just being obtuse and am missing something super obvious, but it appears to be attempting to fetch remote images from the localhost instance and not the `baseUrl` defined in the config.

I'm using the same `baseUrl` and `protocol` as the `gatsby-source-wordpress` plugin's options.

```javascript
(...gastby-source-wordpress-config),
plugins: [
  {
    resolve: `gatsby-wordpress-inline-images`,
    options: {
      baseUrl: `my-wordpress-website.test`,
      protocol: `https`
    }
  }
],
```

![Screen Shot 2019-04-30 at 11 41 43 am](https://user-images.githubusercontent.com/12944411/56940045-9f85c800-6b3e-11e9-9600-ea994250a3fe.png)

**Comment by TylerBarnes** [comment]
Weird. Does `my-wordpress-website.test` resolve to localhost? Or maybe do your inline images have localhost:8000 hardcoded in their src's in `post_content`?

**Comment by glennforrest** [comment]
Alrighty, so I had the below in the `wordpress source` config, so yeah effectively it had `localhost:8000` in the post content by the time `inline` started processing.

```javascript
searchAndReplaceContentUrls: {
  sourceUrl: `https://my-wordpress-website.test`,
  replacementUrl: `https://localhost:8000`,
},
```

Reckon there's still legitimate reason to still want to use the `searchAndReplaceContentUrls` config? Like links to files hosted on the WordPress site?

**Comment by TylerBarnes** [comment]
@glennforrest you can still use search and replace but you have to do a regex that matches `https://my-wordpress-website.test` but not `https://my-wordpress-website.test/wp-content/etc`

**Comment by TylerBarnes** [comment]
for ex `https:\/\/my-wordpress-website.test(?!\/wp-content)` (probably needs to be tweaked a bit)
